SELECT TOP 3 *
FROM DBO.tx_deathrow;

SELECT TOP 3 FIRST_NAME, LAST_NAME 
FROM DBO.tx_deathrow;

SELECT TOP 3 FIRST_NAME 
FROM DBO.tx_deathrow;

SELECT 50/2, 51/2;

SELECT FIRST_NAME, LAST_NAME 
FROM DBO.tx_deathrow 
WHERE EXECUTION = 145;

SELECT FIRST_NAME, LAST_NAME, AGE_AT_EXECUTION 
FROM tx_deathrow 
WHERE AGE_AT_EXECUTION <= 25;

SELECT FIRST_NAME, LAST_NAME, EXECUTION 
FROM DBO.tx_deathrow 
WHERE FIRST_NAME = 'RAYMOND' 
  AND LAST_NAME LIKE '%LANDRY%';

SELECT FIRST_NAME, LAST_NAME, LAST_STATEMENT 
FROM DBO.tx_deathrow 
WHERE FIRST_NAME LIKE 'NAPOLEON';

SELECT COUNT(LAST_STATEMENT) 
FROM DBO.tx_deathrow;

SELECT COUNT(EXECUTION) 
FROM DBO.tx_deathrow;

SELECT COUNT(*) 
FROM DBO.tx_deathrow;

SELECT 
  COUNT(CASE WHEN county = 'Harris' THEN 1 ELSE NULL END), 
  COUNT(CASE WHEN county = 'Bexar' THEN 1 ELSE NULL END) 
FROM DBO.tx_deathrow;


SELECT COUNT(EXECUTION) 
FROM dbo.tx_deathrow 
WHERE AGE_AT_EXECUTION > 50;

SELECT COUNT(EXECUTION) 
FROM DBO.tx_deathrow 
WHERE LAST_STATEMENT IS NULL;


SELECT MIN(AGE_AT_EXECUTION), MAX(AGE_AT_EXECUTION), AVG(AGE_AT_EXECUTION) 
FROM DBO.tx_deathrow;

SELECT AVG(DATALENGTH(LAST_STATEMENT)) 
FROM DBO.tx_deathrow;

SELECT 
  county, 
  COUNT(*) AS county_executions 
FROM DBO.tx_deathrow 
GROUP BY county;

SELECT COUNTY, COUNT(*) 
FROM DBO.tx_deathrow 
WHERE AGE_AT_EXECUTION >= 50 
GROUP BY COUNTY;

SELECT COUNTY 
FROM DBO.tx_deathrow 
WHERE AGE_AT_EXECUTION >= 50 
GROUP BY COUNTY 
HAVING COUNT(*) > 2;

SELECT DISTINCT COUNTY 
FROM dbo.tx_deathrow 
GROUP BY COUNTY;

SELECT first_name, last_name 
FROM DBO.tx_deathrow 
WHERE DATALENGTH(last_statement) = 
  (SELECT MAX(DATALENGTH(LAST_STATEMENT)) 
   FROM DBO.tx_deathrow);

SELECT 
  county, 
  100.0 * COUNT(*) / (SELECT COUNT(*) FROM dbo.tx_deathrow) AS percentage 
FROM dbo.tx_deathrow 
GROUP BY county 
ORDER BY percentage DESC;